// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web_app_Csharp.Data;

#nullable disable

namespace web_app_Csharp.Migrations
{
    [DbContext(typeof(BankContext))]
    [Migration("20260222130306_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("web_app_Csharp.Models.SecureAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasDiscriminator<string>("Discriminator").HasValue("SecureAccount");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("web_app_Csharp.Models.CheckingAccount", b =>
                {
                    b.HasBaseType("web_app_Csharp.Models.SecureAccount");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("CheckingAccount");
                });

            modelBuilder.Entity("web_app_Csharp.Models.RetirementAccount", b =>
                {
                    b.HasBaseType("web_app_Csharp.Models.SecureAccount");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("TEXT");

                    b.ToTable("Accounts", t =>
                        {
                            t.Property("InterestRate")
                                .HasColumnName("RetirementAccount_InterestRate");
                        });

                    b.HasDiscriminator().HasValue("RetirementAccount");
                });

            modelBuilder.Entity("web_app_Csharp.Models.SavingAccount", b =>
                {
                    b.HasBaseType("web_app_Csharp.Models.SecureAccount");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("SavingAccount");
                });
#pragma warning restore 612, 618
        }
    }
}
